import { pgTable, text, integer, real, boolean, timestamp, jsonb, primaryKey, uniqueIndex } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };
export const datasetVersions = pgTable("dataset_versions", { datasetVersion: text("dataset_version").primaryKey(), datasetDate: text("dataset_date"), scoreVersion: text("score_version"), silverRows: integer("silver_rows"), goldRows: integer("gold_rows"), priorityCounts: jsonb("priority_counts"), publishedAt: timestamp("published_at", { withTimezone: true }), ...timestamps });
export const firms = pgTable("firms", { firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), name: text("name"), primaryBusinessName: text("primary_business_name"), secNumber: text("sec_number"), websiteAddress: text("website_address"), organizationState: text("organization_state"), secRegion: text("sec_region"), secCurrentStatus: text("sec_current_status"), ...timestamps }, t => ({ pk: primaryKey({ columns: [t.firmId, t.datasetVersion] }), firmIdx: uniqueIndex("firms_firm_dataset_idx").on(t.firmId, t.datasetVersion) }));
export const firmFacts = pgTable("firm_facts", { firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), totalAum: real("total_aum"), discretionaryAum: real("discretionary_aum"), nonDiscretionaryAum: real("non_discretionary_aum"), totalAccountCount: integer("total_account_count"), averageAccountSize: real("average_account_size"), individualHnwShare: real("individual_hnw_share"), employeeCount: integer("employee_count"), advisoryEmployeeCount: integer("advisory_employee_count"), stateIarCount: integer("state_iar_count"), hasItem11Disclosure: boolean("has_item_11_disclosure"), regulatoryReviewFlag: boolean("regulatory_review_flag"), mainOfficeStreetAddress1: text("main_office_street_address_1"), mainOfficeStreetAddress2: text("main_office_street_address_2"), mainOfficeCity: text("main_office_city"), mainOfficeState: text("main_office_state"), mainOfficeCountry: text("main_office_country"), mainOfficePhone: text("main_office_phone"), ...timestamps }, t => ({ pk: primaryKey({ columns: [t.firmId, t.datasetVersion] }) }));
export const firmScores = pgTable("firm_scores", { firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), acquisitionScore: real("acquisition_score"), priorityCategory: text("priority_category"), priorityReadiness: text("priority_readiness"), reviewRequired: boolean("review_required"), componentScores: jsonb("component_scores"), reasonCodes: jsonb("reason_codes"), ...timestamps }, t => ({ pk: primaryKey({ columns: [t.firmId, t.datasetVersion] }) }));
export const firmResearch = pgTable("firm_research", { firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), researchStatus: text("research_status").notNull().default("NOT_STARTED"), researchOwner: text("research_owner"), founderName: text("founder_name"), founderRole: text("founder_role"), ownershipType: text("ownership_type"), ownershipSummary: text("ownership_summary"), successionReadinessAssessment: text("succession_readiness_assessment"), investmentPhilosophy: text("investment_philosophy"), primaryCustodian: text("primary_custodian"), strategicFitAssessment: text("strategic_fit_assessment"), transitionFeasibility: text("transition_feasibility"), integrationRisks: text("integration_risks"), ...timestamps }, t => ({ pk: primaryKey({ columns: [t.firmId, t.datasetVersion] }) }));
export const researchSources = pgTable("research_sources", { sourceId: text("source_id").primaryKey(), firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), sourceType: text("source_type").notNull(), sourceUrl: text("source_url"), sourceTitle: text("source_title"), sourceAuthority: text("source_authority"), accessedAt: timestamp("accessed_at", { withTimezone: true }), retrievalStatus: text("retrieval_status"), contentHash: text("content_hash"), fieldSupported: text("field_supported"), sourceNotes: text("source_notes"), ...timestamps });
export const evidenceCaptures = pgTable("research_evidence_captures", { captureId: text("capture_id").primaryKey(), sourceId: text("source_id").notNull(), scrapeId: text("scrape_id"), extractionMethod: text("extraction_method"), contentType: text("content_type"), content: text("content"), metadata: jsonb("metadata"), contentHash: text("content_hash"), ...timestamps });
export const observations = pgTable("research_observations", { observationId: text("observation_id").primaryKey(), firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), sourceId: text("source_id").notNull(), canonicalField: text("canonical_field").notNull(), proposedValue: text("proposed_value"), valueType: text("value_type").notNull(), confidence: text("confidence"), reviewStatus: text("review_status").notNull().default("PROPOSED"), reviewer: text("reviewer"), reviewedAt: timestamp("reviewed_at", { withTimezone: true }), reviewNotes: text("review_notes"), ...timestamps });
export const contacts = pgTable("contacts", { contactId: text("contact_id").primaryKey(), firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), contactName: text("contact_name"), title: text("title"), decisionMakerType: text("decision_maker_type"), email: text("email"), phone: text("phone"), profileUrl: text("profile_url"), contactConfidence: text("contact_confidence"), identityConfidence: text("identity_confidence"), verificationStatus: text("verification_status"), analystNotes: text("analyst_notes"), ...timestamps });
export const outreachTargets = pgTable("outreach_targets", { firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), status: text("status").notNull().default("NOT_RESEARCHED"), primaryContactId: text("primary_contact_id"), assignedTo: text("assigned_to"), lastActivityAt: timestamp("last_activity_at", { withTimezone: true }), nextAction: text("next_action"), nextActionDate: text("next_action_date"), notes: text("notes"), ...timestamps }, t => ({ pk: primaryKey({ columns: [t.firmId, t.datasetVersion] }) }));
export const outreachActivities = pgTable("outreach_activities", { activityId: text("activity_id").primaryKey(), firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), activityType: text("activity_type").notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), notes: text("notes"), createdBy: text("created_by"), ...timestamps });
export const outreachStatusHistory = pgTable("outreach_status_history", { historyId: text("history_id").primaryKey(), firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), fromStatus: text("from_status"), toStatus: text("to_status").notNull(), changedBy: text("changed_by"), changedAt: timestamp("changed_at", { withTimezone: true }).defaultNow().notNull(), notes: text("notes") });
export const pipelineRuns = pgTable("pipeline_runs", { runId: text("run_id").primaryKey(), datasetVersion: text("dataset_version"), status: text("status"), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), durationSeconds: real("duration_seconds"), details: jsonb("details") });
export const pipelineStages = pgTable("pipeline_stages", { stageId: text("stage_id").primaryKey(), runId: text("run_id"), stageName: text("stage_name"), status: text("status"), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), durationSeconds: real("duration_seconds"), details: jsonb("details") });
export const alerts = pgTable("alerts", { alertId: text("alert_id").primaryKey(), eventType: text("event_type"), severity: text("severity"), message: text("message"), createdAt: timestamp("created_at", { withTimezone: true }), acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }) });
export const backupMetadata = pgTable("backup_metadata", { backupId: text("backup_id").primaryKey(), datasetVersion: text("dataset_version"), createdAt: timestamp("created_at", { withTimezone: true }), status: text("status"), manifest: jsonb("manifest") });
export const changeIntelligence = pgTable("change_intelligence", { changeId: text("change_id").primaryKey(), datasetVersion: text("dataset_version"), firmId: text("firm_id"), eventType: text("event_type"), details: jsonb("details"), createdAt: timestamp("created_at", { withTimezone: true }) });
export const researchRefreshQueue = pgTable("research_refresh_queue", { queueId: text("queue_id").primaryKey(), firmId: text("firm_id"), datasetVersion: text("dataset_version"), reason: text("reason"), status: text("status"), createdAt: timestamp("created_at", { withTimezone: true }) });
export const enrichmentJobs = pgTable("enrichment_jobs", { jobId: text("job_id").primaryKey(), firmId: text("firm_id").notNull(), datasetVersion: text("dataset_version").notNull(), status: text("status").notNull(), requestedBy: text("requested_by"), errorMessage: text("error_message"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), completedAt: timestamp("completed_at", { withTimezone: true }) });
// SEC IAPD compilation-feed enrichment. These records are monthly person-level
// snapshots and deliberately remain separate from the Form ADV firm master.
export const iapdIndividualSnapshots = pgTable("iapd_individual_snapshots", { snapshotId: text("snapshot_id").primaryKey(), snapshotDate: text("snapshot_date").notNull(), sourceUrl: text("source_url").notNull(), sourceFileName: text("source_file_name").notNull(), sourceZipPath: text("source_zip_path"), contentHash: text("content_hash").notNull(), status: text("status").notNull(), individualCount: integer("individual_count"), changeSummary: jsonb("change_summary"), downloadedAt: timestamp("downloaded_at", { withTimezone: true }), parsedAt: timestamp("parsed_at", { withTimezone: true }), ...timestamps }, t => ({ hashIdx: uniqueIndex("iapd_snapshot_hash_idx").on(t.contentHash), dateIdx: uniqueIndex("iapd_snapshot_date_idx").on(t.snapshotDate) }));
export const iapdIndividuals = pgTable("iapd_individuals", { individualCrd: text("individual_crd").primaryKey(), firstName: text("first_name"), middleName: text("middle_name"), lastName: text("last_name"), suffix: text("suffix"), fullName: text("full_name"), activeAgRegistration: boolean("active_ag_registration"), compositeLink: text("composite_link"), lastSnapshotId: text("last_snapshot_id") , ...timestamps });
export const iapdIndividualSnapshotMembers = pgTable("iapd_individual_snapshot_members", { snapshotId: text("snapshot_id").notNull(), individualCrd: text("individual_crd").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ pk: primaryKey({ columns: [t.snapshotId, t.individualCrd] }), crdIdx: uniqueIndex("iapd_snapshot_member_crd_idx").on(t.snapshotId, t.individualCrd) }));
export const iapdIndividualAliases = pgTable("iapd_individual_aliases", { aliasId: text("alias_id").primaryKey(), snapshotId: text("snapshot_id").notNull(), individualCrd: text("individual_crd").notNull(), aliasName: text("alias_name").notNull(), firstName: text("first_name"), middleName: text("middle_name"), lastName: text("last_name"), suffix: text("suffix"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ crdIdx: uniqueIndex("iapd_alias_snapshot_crd_idx").on(t.snapshotId, t.individualCrd, t.aliasId) }));
export const iapdIndividualCurrentEmployments = pgTable("iapd_individual_current_employments", { employmentId: text("employment_id").primaryKey(), snapshotId: text("snapshot_id").notNull(), individualCrd: text("individual_crd").notNull(), employerFirmCrd: text("employer_firm_crd"), employerName: text("employer_name"), addressLine1: text("address_line_1"), addressLine2: text("address_line_2"), city: text("city"), state: text("state"), postalCode: text("postal_code"), country: text("country"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ firmIdx: uniqueIndex("iapd_current_employment_firm_idx").on(t.snapshotId, t.employerFirmCrd, t.employmentId), crdIdx: uniqueIndex("iapd_current_employment_crd_idx").on(t.snapshotId, t.individualCrd, t.employmentId) }));
export const iapdIndividualCurrentRegistrations = pgTable("iapd_individual_current_registrations", { registrationId: text("registration_id").primaryKey(), snapshotId: text("snapshot_id").notNull(), employmentId: text("employment_id").notNull(), individualCrd: text("individual_crd").notNull(), authority: text("authority"), category: text("category"), status: text("status"), statusDate: text("status_date"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ crdIdx: uniqueIndex("iapd_current_registration_crd_idx").on(t.snapshotId, t.individualCrd, t.registrationId) }));
export const iapdIndividualPreviousRegistrations = pgTable("iapd_individual_previous_registrations", { previousRegistrationId: text("previous_registration_id").primaryKey(), snapshotId: text("snapshot_id").notNull(), individualCrd: text("individual_crd").notNull(), employerFirmCrd: text("employer_firm_crd"), employerName: text("employer_name"), authority: text("authority"), category: text("category"), status: text("status"), beginDate: text("begin_date"), endDate: text("end_date"), addressLine1: text("address_line_1"), addressLine2: text("address_line_2"), city: text("city"), state: text("state"), postalCode: text("postal_code"), country: text("country"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ crdIdx: uniqueIndex("iapd_previous_registration_crd_idx").on(t.snapshotId, t.individualCrd, t.previousRegistrationId) }));
export const iapdIndividualEmploymentHistory = pgTable("iapd_individual_employment_history", { historyId: text("history_id").primaryKey(), snapshotId: text("snapshot_id").notNull(), individualCrd: text("individual_crd").notNull(), organizationName: text("organization_name"), city: text("city"), state: text("state"), fromDate: text("from_date"), toDate: text("to_date"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ crdIdx: uniqueIndex("iapd_employment_history_crd_idx").on(t.snapshotId, t.individualCrd, t.historyId) }));
export const iapdIndividualBranchLocations = pgTable("iapd_individual_branch_locations", { branchId: text("branch_id").primaryKey(), snapshotId: text("snapshot_id").notNull(), employmentId: text("employment_id"), individualCrd: text("individual_crd").notNull(), employerFirmCrd: text("employer_firm_crd"), branchName: text("branch_name"), addressLine1: text("address_line_1"), addressLine2: text("address_line_2"), city: text("city"), state: text("state"), postalCode: text("postal_code"), country: text("country"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ firmIdx: uniqueIndex("iapd_branch_firm_idx").on(t.snapshotId, t.employerFirmCrd, t.branchId) }));
export const iapdIndividualOtherBusinesses = pgTable("iapd_individual_other_businesses", { otherBusinessId: text("other_business_id").primaryKey(), snapshotId: text("snapshot_id").notNull(), individualCrd: text("individual_crd").notNull(), description: text("description").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ crdIdx: uniqueIndex("iapd_other_business_crd_idx").on(t.snapshotId, t.individualCrd, t.otherBusinessId) }));
export const iapdIndividualDisclosureFlags = pgTable("iapd_individual_disclosure_flags", { disclosureId: text("disclosure_id").primaryKey(), snapshotId: text("snapshot_id").notNull(), individualCrd: text("individual_crd").notNull(), regAction: boolean("reg_action"), criminal: boolean("criminal"), bankrupt: boolean("bankrupt"), civilJudgment: boolean("civil_judgment"), bond: boolean("bond"), judgment: boolean("judgment"), investigation: boolean("investigation"), customerComplaint: boolean("customer_complaint"), termination: boolean("termination"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ crdIdx: uniqueIndex("iapd_disclosure_crd_idx").on(t.snapshotId, t.individualCrd, t.disclosureId) }));
export const iapdIndividualChanges = pgTable("iapd_individual_changes", { changeId: text("change_id").primaryKey(), snapshotId: text("snapshot_id").notNull(), individualCrd: text("individual_crd").notNull(), eventType: text("event_type").notNull(), details: jsonb("details"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ snapshotIdx: uniqueIndex("iapd_change_snapshot_idx").on(t.snapshotId, t.eventType, t.individualCrd) }));
// Live IAPD captures are a fallback/enrichment layer. They never overwrite
// the monthly feed; reconciliation retains both values and any conflicts.
export const iapdImportIssues = pgTable("iapd_import_issues", { issueId: text("issue_id").primaryKey(), snapshotId: text("snapshot_id"), individualCrd: text("individual_crd"), stage: text("stage").notNull(), severity: text("severity").notNull(), issueCode: text("issue_code").notNull(), message: text("message").notNull(), details: jsonb("details"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ snapshotIdx: uniqueIndex("iapd_import_issue_idx").on(t.snapshotId, t.issueId) }));
export const iapdLiveCaptures = pgTable("iapd_live_captures", { captureId: text("capture_id").primaryKey(), individualCrd: text("individual_crd").notNull(), sourceUrl: text("source_url").notNull(), sourceTitle: text("source_title"), retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(), retrievalStatus: text("retrieval_status").notNull(), contentHash: text("content_hash").notNull(), parserVersion: text("parser_version").notNull(), rawPayload: jsonb("raw_payload"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ crdIdx: uniqueIndex("iapd_live_capture_crd_idx").on(t.individualCrd, t.captureId) }));
export const iapdIndividualLiveEnrichments = pgTable("iapd_individual_live_enrichments", { enrichmentId: text("enrichment_id").primaryKey(), captureId: text("capture_id").notNull(), individualCrd: text("individual_crd").notNull(), fullName: text("full_name"), currentEmployerName: text("current_employer_name"), currentEmployerCrd: text("current_employer_crd"), businessAddress: text("business_address"), phone: text("phone"), website: text("website"), registrationStatus: text("registration_status"), registrationDate: text("registration_date"), branchLocations: jsonb("branch_locations"), disclosureSummary: text("disclosure_summary"), normalizedFields: jsonb("normalized_fields").notNull(), confidence: text("confidence").notNull(), freshness: text("freshness").notNull(), retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ crdIdx: uniqueIndex("iapd_live_enrichment_crd_idx").on(t.individualCrd, t.enrichmentId) }));
export const iapdIndividualReconciliations = pgTable("iapd_individual_reconciliations", { reconciliationId: text("reconciliation_id").primaryKey(), individualCrd: text("individual_crd").notNull(), snapshotId: text("snapshot_id"), captureId: text("capture_id"), effectiveFields: jsonb("effective_fields").notNull(), freshness: text("freshness").notNull(), confidence: text("confidence").notNull(), conflicts: jsonb("conflicts").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => ({ crdIdx: uniqueIndex("iapd_reconciliation_crd_idx").on(t.individualCrd, t.reconciliationId) }));
export const users = pgTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), passwordHash: text("password_hash").notNull(), name: text("name"), role: text("role").notNull().default("analyst") });
